name: TestRVModel

on:
  push:
    branches:
    - main
    - interpreter
  pull_request:
    branches:
    - main
    - interpreter

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: ujenetort/rv32_interpreter:latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: build release
      run: |
        mkdir build_release && cd build_release
        cmake .. -G Ninja -DCMAKE_CXX_COMPILER=clang++-21 \
                 -DCMAKE_CXX_STANDARD=20 \
                 -DCMAKE_BUILD_TYPE=Release \
                 -DLLVM_DIR=/usr/lib/llvm-21/cmake
        ninja
      shell: bash

    - name: build debug
      run: |
        mkdir build_debug && cd build_debug
        cmake .. -G Ninja -DCMAKE_CXX_COMPILER=clang++-21 \
                 -DCMAKE_CXX_STANDARD=20 \
                 -DCMAKE_BUILD_TYPE=Debug \
                 -DLLVM_DIR=/usr/lib/llvm-21/cmake
        ninja
      shell: bash

    - name: upload build debug artifacts
      uses: actions/upload-artifact@v4
      with:
        name: interpreter_build_debug
        path: build_debug/
        retention-days: 1

    - name: upload build release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: interpreter_build_release
        path: build_release/
        retention-days: 1

  test_debug:
    runs-on: ubuntu-24.04
    needs: build

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: interpreter_build_debug
        path: build_debug/

    - name: Fix permissions
      run: chmod +x build_debug/test

    - name: test_dbg
      run: ./test
      working-directory: build_debug
      shell: bash

  test_release:
    runs-on: ubuntu-24.04
    needs: build

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: interpreter_build_release
        path: build_release/

    - name: Fix permissions
      run: chmod +x build_release/test

    - name: test_release
      run: ./test
      working-directory: build_release
      shell: bash
