name: TestRVModel

on:
  push:
    branches:
    - main
    - interpreter
  pull_request:
    branches:
    - main
    - interpreter

jobs:
  test_model:
    runs-on: ubuntu-22.04
    steps:
    - name: install LLVM 21
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 21
        sudo apt update
    - name: install prerequisites
      run: |
        sudo apt update
        sudo apt install clang-21 libllvm21 cmake ninja-build build-essential libgtest-dev libboost-all-dev
      shell: bash

    - name: checkout
      uses: actions/checkout@v4

    - name: update submodule
      run: |
        git submodule update --init --recursive
      shell: bash

    - name: build release
      run: |
        mkdir build_sh_release && cd build_sh_release
        cmake .. -G Ninja -DCMAKE_CXX_COMPILER=clang++-21 \
                 -DCMAKE_CXX_STANDARD=20 \
                 -DCMAKE_BUILD_TYPE=Release \
                 -DLLVM_DIR=/usr/lib/llvm-21/cmake
        ninja
      shell: bash

    - name: build debug
      run: |
        mkdir build_sh_debug && cd build_sh_debug
        cmake .. -G Ninja -DCMAKE_CXX_COMPILER=clang++-21 \
                 -DCMAKE_CXX_STANDARD=20 \
                 -DCMAKE_BUILD_TYPE=Debug \
                 -DLLVM_DIR=/usr/lib/llvm-21/cmake
        ninja
      shell: bash

    - name: test_plus
      run: ./test --gtest_filter=TestRVModel.PLUS
      working-directory: build_sh_release
      shell: bash

    - name: test_factorial
      run: ./test --gtest_filter=TestRVModel.FACTORIAL
      working-directory: build_sh_release
      shell: bash

    - name: test_echo
      run: ./test --gtest_filter=TestRVModel.ECHO
      working-directory: build_sh_release
      shell: bash

    - name: test_plus_dbg
      run: ./test --gtest_filter=TestRVModel.PLUS
      working-directory: build_sh_debug
      shell: bash

    - name: test_factorial_dbg
      run: ./test --gtest_filter=TestRVModel.FACTORIAL
      working-directory: build_sh_debug
      shell: bash

    - name: test_echo_dbg
      run: ./test --gtest_filter=TestRVModel.ECHO
      working-directory: build_sh_debug
      shell: bash

